######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 18 17:17:52 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += AnimateBounceEasyCurve.cpp
