######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 18 17:18:50 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwin.h
SOURCES += main.cpp mainwin.cpp
