######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 18 17:20:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += AnimateStateMachine.cpp
