######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 18 17:19:12 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MovingButton.h
SOURCES += AnimateTimer.cpp MovingButton.cpp
